pipeline {
    agent any

    environment {
        REMOTE_USER = 'remote_user'
        REMOTE_HOST = 'remote-host'
        MYSQL_HOST = 'db'
        MYSQL_PASSWORD = '1234'
        DATABASE_NAME = 'your_database'
        AWS_ACCESS_KEY = 'your_aws_key'
        AWS_BUCKET_NAME = 'your_bucket_name'
    }

    stages {
        stage('Run MySQL Backup Script') {
            steps {
                sshagent (credentials: ['remote-ssh-key']) {
                    sh '''
                        ssh -o StrictHostKeyChecking=no $REMOTE_USER@$REMOTE_HOST "\
                        bash /tmp/backup_process.sh $MYSQL_HOST $MYSQL_PASSWORD $DATABASE_NAME $AWS_ACCESS_KEY $AWS_BUCKET_NAME"
                    '''
                }
            }
        }
    }
}

